type ServiceCenterLocale = 'en' | 'zh-TW' | 'zh' | 'ja' | 'ko' | 'fr' | 'es' | 'de' | 'pt' | 'ru' | 'ar'

const en = {
  title: 'Service Center', subtitle: 'Your registered tools and web services, in one place.', reachability: 'Network access depends on your device. A backend check does not verify browser reachability.',
  refresh: 'Refresh', export: 'Export JSON', import: 'Import JSON', add: 'Add service', edit: 'Edit', delete: 'Delete', favorite: 'Add to favorites', unfavorite: 'Remove from favorites', favorites: 'Favorites',
  search: 'Search name, category or tag', categoryFilter: 'Category', allCategories: 'All categories', noMatches: 'No matching services.', empty: 'No services registered yet.', loading: 'Loading services…', noDescription: 'No description',
  check: 'Check backend', approve: 'Approve check', revokeApproval: 'Revoke check', approveConfirm: 'Allow this server to send a GET request to the registered health URL for {name}? This may reach a private network.', approved: 'Health target approved', revoked: 'Health approval revoked', approvalHint: 'Health checks need a separate server-side approval. Import never approves a target.',
  permissions: 'Editors', permissionsTitle: 'Service Center editors', permissionsHint: 'Only active admins can receive Service Center editing access. This does not change their Studio role.', grant: 'Grant editing', revoke: 'Revoke editing', noAdmins: 'No active admins', permissionSaved: 'Editor access updated',
  editTitle: 'Edit service', addTitle: 'Register service', id: 'Stable ID', name: 'Name', description: 'Description', url: 'Web address', iconLabel: 'Icon', category: 'Category', networkLabel: 'Network', sortOrder: 'Sort order', tags: 'Tags', tagsHint: 'Comma-separated tags', healthUrl: 'Health GET URL', enabled: 'Visible', healthEnabled: 'Enable health check', save: 'Save', cancel: 'Cancel', saved: 'Service saved', deleted: 'Service deleted', deleteConfirm: 'Delete {name}? This removes its registration.',
  importTitle: 'Import manifest', importHint: 'Merge by stable ID. Existing entries require an explicit keep or overwrite choice. No services are deleted and no health targets are approved.', chooseFile: 'Choose JSON manifest', fileTooLarge: 'The manifest is too large.', invalidJson: 'Invalid JSON file', preview: 'Preview import', importSummary: '{count} entries: {fresh} new, {conflicts} existing', conflictChoice: 'Choice for {id}', keep: 'Keep current', overwrite: 'Overwrite', confirmImport: 'Confirm import', imported: 'Manifest imported', failed: 'Operation failed', reload: 'Reload catalog',
  network: { tailscale: 'Tailscale', lan: 'Local network', public: 'Public', local: 'This device' },
  icon: { globe: 'Globe', server: 'Server', cloud: 'Cloud', tool: 'Tool', database: 'Database', monitor: 'Monitor', folder: 'Folder', shield: 'Shield' },
  health: { untested: 'Not checked', stale: 'Previous result (stale)', unapproved: 'Not approved', disabled: 'Check off', healthy: 'Backend responding', http_error: 'Backend HTTP error', redirected: 'Redirect (not followed)', timeout: 'Timed out', unreachable: 'Unreachable', blocked: 'Blocked target', busy: 'Check limited' },
}
type Messages = typeof en
type Overrides = Omit<Partial<Messages>, 'network' | 'icon' | 'health'> & {
  network?: Partial<Messages['network']>
  icon?: Partial<Messages['icon']>
  health?: Partial<Messages['health']>
}
const localized = (overrides: Overrides): Messages => ({ ...en, ...overrides, network: { ...en.network, ...overrides.network }, icon: { ...en.icon, ...overrides.icon }, health: { ...en.health, ...overrides.health } })

export const serviceCenterMessages: Record<ServiceCenterLocale, Messages> = {
  en,
  'zh-TW': localized({ title: '服務中心', subtitle: '集中管理已登記的工具與網頁服務。', reachability: '連線取決於你的裝置網路；後端檢查不代表瀏覽器可開啟。', refresh: '重新整理', export: '匯出 JSON', import: '匯入 JSON', add: '新增服務', edit: '編輯', delete: '刪除', favorite: '加入收藏', unfavorite: '取消收藏', favorites: '收藏', search: '搜尋名稱、分類或標籤', categoryFilter: '分類', allCategories: '所有分類', noMatches: '沒有符合的服務。', empty: '尚未登記服務。', loading: '正在載入服務…', noDescription: '沒有說明', check: '檢查後端', approve: '核准檢查', revokeApproval: '撤銷核准', approveConfirm: '允許伺服器對「{name}」登記的健康檢查網址發送 GET 請求嗎？這可能連到私人網路。', approved: '已核准健康檢查目標', revoked: '已撤銷檢查核准', approvalHint: '健康檢查需要另外由伺服端核准；匯入不會自動核准。', permissions: '編輯權限', permissionsTitle: '服務中心編輯者', permissionsHint: '只有使用中的管理員可取得服務中心編輯權，不變更 Studio 角色。', grant: '授予編輯權', revoke: '撤銷編輯權', noAdmins: '沒有使用中的管理員', permissionSaved: '已更新編輯權', editTitle: '編輯服務', addTitle: '登記服務', id: '固定 ID', name: '名稱', description: '說明', url: '網頁位址', iconLabel: '圖示', category: '分類', networkLabel: '網路', sortOrder: '排序', tags: '標籤', tagsHint: '以逗號分隔標籤', healthUrl: '健康檢查 GET 網址', enabled: '顯示', healthEnabled: '啟用健康檢查', save: '儲存', cancel: '取消', saved: '已儲存服務', deleted: '已刪除服務', deleteConfirm: '刪除「{name}」的登記資料？', importTitle: '匯入 manifest', importHint: '依固定 ID 合併；既有項目需明確選擇保留或覆寫。不會刪除服務或核准檢查目標。', chooseFile: '選擇 JSON manifest', fileTooLarge: 'manifest 檔案過大。', invalidJson: 'JSON 檔案無效', preview: '預覽匯入', importSummary: '共 {count} 筆：新增 {fresh}、既有 {conflicts}', conflictChoice: '{id} 的處理方式', keep: '保留現有', overwrite: '覆寫', confirmImport: '確認匯入', imported: '已匯入 manifest', failed: '操作失敗', reload: '重新載入目錄', network: { tailscale: 'Tailscale', lan: '區域網路', public: '公開網路', local: '本機' }, icon: { globe: '地球', server: '伺服器', cloud: '雲端', tool: '工具', database: '資料庫', monitor: '螢幕', folder: '資料夾', shield: '防護' }, health: { untested: '尚未檢查', unapproved: '未核准', disabled: '未啟用檢查', healthy: '後端有回應', http_error: '後端 HTTP 錯誤', redirected: '重新導向（未跟隨）', timeout: '逾時', unreachable: '無法連線', blocked: '已封鎖目標', busy: '檢查頻率受限' } }),
  zh: localized({ title: '服务中心', subtitle: '集中管理已登记的工具与网页服务。', reachability: '连接取决于设备网络；后端检查不代表浏览器可访问。', refresh: '刷新', export: '导出 JSON', import: '导入 JSON', add: '添加服务', edit: '编辑', delete: '删除', favorite: '加入收藏', unfavorite: '取消收藏', favorites: '收藏', search: '搜索名称、分类或标签', categoryFilter: '分类', allCategories: '所有分类', noMatches: '没有匹配的服务。', empty: '尚未登记服务。', loading: '正在加载服务…', noDescription: '没有说明', check: '检查后端', approve: '批准检查', revokeApproval: '撤销批准', approveConfirm: '允许服务器对“{name}”登记的健康检查网址发送 GET 请求吗？可能连接私人网络。', approved: '已批准健康检查目标', revoked: '已撤销批准', approvalHint: '健康检查需要另外由服务器批准；导入不会自动批准。', permissions: '编辑权限', permissionsTitle: '服务中心编辑者', permissionsHint: '仅活跃管理员可获得服务中心编辑权限，不改变 Studio 角色。', grant: '授予编辑权', revoke: '撤销编辑权', noAdmins: '没有活跃管理员', permissionSaved: '编辑权已更新', editTitle: '编辑服务', addTitle: '登记服务', id: '固定 ID', name: '名称', description: '说明', url: '网页地址', iconLabel: '图标', category: '分类', networkLabel: '网络', sortOrder: '排序', tags: '标签', tagsHint: '逗号分隔标签', healthUrl: '健康检查 GET 地址', enabled: '显示', healthEnabled: '启用健康检查', save: '保存', cancel: '取消', saved: '服务已保存', deleted: '服务已删除', deleteConfirm: '删除“{name}”的登记信息？', importTitle: '导入 manifest', importHint: '按固定 ID 合并；已有项目需明确选择保留或覆盖。不删除服务或批准检查目标。', chooseFile: '选择 JSON manifest', fileTooLarge: 'manifest 文件过大。', invalidJson: 'JSON 文件无效', preview: '预览导入', importSummary: '共 {count} 条：新增 {fresh}、已有 {conflicts}', conflictChoice: '{id} 的处理方式', keep: '保留当前', overwrite: '覆盖', confirmImport: '确认导入', imported: 'manifest 已导入', failed: '操作失败', reload: '重新加载目录', network: { tailscale: 'Tailscale', lan: '局域网', public: '公网', local: '本机' }, icon: { globe: '地球', server: '服务器', cloud: '云', tool: '工具', database: '数据库', monitor: '屏幕', folder: '文件夹', shield: '防护' }, health: { untested: '尚未检查', unapproved: '未批准', disabled: '未启用检查', healthy: '后端有响应', http_error: '后端 HTTP 错误', redirected: '重定向（未跟随）', timeout: '超时', unreachable: '无法连接', blocked: '已拦截目标', busy: '检查频率受限' } }),
  ja: localized({ title: 'サービスセンター', subtitle: '登録済みのツールとウェブサービスを一覧表示。', reachability: '接続には端末のネットワークが必要です。バックエンド検査はブラウザーからの到達性を保証しません。', refresh: '更新', export: 'JSON を出力', import: 'JSON を読み込む', add: 'サービスを追加', edit: '編集', delete: '削除', favorite: 'お気に入りに追加', unfavorite: 'お気に入りを解除', favorites: 'お気に入り', search: '名前・カテゴリ・タグを検索', categoryFilter: 'カテゴリ', allCategories: 'すべて', noMatches: '一致するサービスはありません。', empty: '登録されたサービスはありません。', loading: '読み込み中…', check: 'バックエンドを検査', approve: '検査を承認', revokeApproval: '承認を取り消す', permissions: '編集権限', permissionsTitle: '編集者', grant: '編集権限を付与', revoke: '編集権限を撤回', save: '保存', cancel: 'キャンセル', network: { tailscale: 'Tailscale', lan: 'ローカルネットワーク', public: '公開', local: 'この端末' }, health: { untested: '未検査', unapproved: '未承認', disabled: '検査無効', healthy: '応答あり', http_error: 'HTTP エラー', redirected: 'リダイレクト', timeout: 'タイムアウト', unreachable: '接続不可', blocked: 'ブロック', busy: '制限中' } }),
  ko: localized({ title: '서비스 센터', subtitle: '등록된 도구와 웹 서비스를 한곳에서 확인하세요.', reachability: '연결은 기기의 네트워크에 따라 다릅니다. 백엔드 검사는 브라우저 접속을 보장하지 않습니다.', refresh: '새로고침', export: 'JSON 내보내기', import: 'JSON 가져오기', add: '서비스 추가', edit: '편집', delete: '삭제', favorite: '즐겨찾기 추가', unfavorite: '즐겨찾기 해제', favorites: '즐겨찾기', search: '이름, 분류 또는 태그 검색', categoryFilter: '분류', allCategories: '모든 분류', noMatches: '일치하는 서비스가 없습니다.', empty: '등록된 서비스가 없습니다.', loading: '서비스 로딩 중…', check: '백엔드 확인', approve: '검사 승인', revokeApproval: '승인 취소', permissions: '편집자', permissionsTitle: '서비스 센터 편집자', grant: '편집 권한 부여', revoke: '편집 권한 회수', save: '저장', cancel: '취소', network: { tailscale: 'Tailscale', lan: '로컬 네트워크', public: '공개', local: '이 기기' }, health: { untested: '확인 안 됨', unapproved: '승인 안 됨', disabled: '검사 꺼짐', healthy: '응답 있음', http_error: 'HTTP 오류', redirected: '리디렉션', timeout: '시간 초과', unreachable: '연결 불가', blocked: '차단됨', busy: '제한됨' } }),
  fr: localized({ title: 'Centre de services', subtitle: 'Vos outils et services Web enregistrés, au même endroit.', reachability: 'L’accès dépend du réseau de votre appareil. Le contrôle du serveur ne garantit pas l’accès depuis le navigateur.', refresh: 'Actualiser', export: 'Exporter JSON', import: 'Importer JSON', add: 'Ajouter un service', edit: 'Modifier', delete: 'Supprimer', favorite: 'Ajouter aux favoris', unfavorite: 'Retirer des favoris', favorites: 'Favoris', search: 'Rechercher nom, catégorie ou tag', categoryFilter: 'Catégorie', allCategories: 'Toutes les catégories', noMatches: 'Aucun service correspondant.', empty: 'Aucun service enregistré.', loading: 'Chargement…', check: 'Vérifier le serveur', approve: 'Autoriser le contrôle', revokeApproval: 'Révoquer l’autorisation', permissions: 'Éditeurs', permissionsTitle: 'Éditeurs du centre', grant: 'Autoriser', revoke: 'Révoquer', save: 'Enregistrer', cancel: 'Annuler', network: { tailscale: 'Tailscale', lan: 'Réseau local', public: 'Public', local: 'Cet appareil' }, health: { untested: 'Non vérifié', unapproved: 'Non autorisé', disabled: 'Contrôle désactivé', healthy: 'Serveur disponible', http_error: 'Erreur HTTP', redirected: 'Redirection', timeout: 'Délai dépassé', unreachable: 'Inaccessible', blocked: 'Bloqué', busy: 'Contrôle limité' } }),
  es: localized({ title: 'Centro de servicios', subtitle: 'Herramientas y servicios web registrados en un solo lugar.', reachability: 'El acceso depende de la red del dispositivo. La comprobación del servidor no garantiza acceso desde el navegador.', refresh: 'Actualizar', export: 'Exportar JSON', import: 'Importar JSON', add: 'Añadir servicio', edit: 'Editar', delete: 'Eliminar', favorite: 'Añadir a favoritos', unfavorite: 'Quitar de favoritos', favorites: 'Favoritos', search: 'Buscar nombre, categoría o etiqueta', categoryFilter: 'Categoría', allCategories: 'Todas las categorías', noMatches: 'No hay servicios coincidentes.', empty: 'No hay servicios registrados.', loading: 'Cargando…', check: 'Comprobar servidor', approve: 'Aprobar comprobación', revokeApproval: 'Revocar aprobación', permissions: 'Editores', permissionsTitle: 'Editores del centro', grant: 'Conceder acceso', revoke: 'Revocar acceso', save: 'Guardar', cancel: 'Cancelar', network: { tailscale: 'Tailscale', lan: 'Red local', public: 'Pública', local: 'Este dispositivo' }, health: { untested: 'Sin comprobar', unapproved: 'Sin aprobar', disabled: 'Comprobación desactivada', healthy: 'Servidor responde', http_error: 'Error HTTP', redirected: 'Redirección', timeout: 'Tiempo agotado', unreachable: 'Inaccesible', blocked: 'Bloqueado', busy: 'Comprobación limitada' } }),
  de: localized({ title: 'Service-Center', subtitle: 'Registrierte Tools und Webdienste an einem Ort.', reachability: 'Der Zugriff hängt vom Gerätenetzwerk ab. Die Serverprüfung belegt keine Erreichbarkeit im Browser.', refresh: 'Aktualisieren', export: 'JSON exportieren', import: 'JSON importieren', add: 'Dienst hinzufügen', edit: 'Bearbeiten', delete: 'Löschen', favorite: 'Zu Favoriten', unfavorite: 'Aus Favoriten entfernen', favorites: 'Favoriten', search: 'Name, Kategorie oder Tag suchen', categoryFilter: 'Kategorie', allCategories: 'Alle Kategorien', noMatches: 'Keine passenden Dienste.', empty: 'Noch keine Dienste registriert.', loading: 'Dienste werden geladen…', check: 'Server prüfen', approve: 'Prüfung genehmigen', revokeApproval: 'Genehmigung widerrufen', permissions: 'Bearbeiter', permissionsTitle: 'Bearbeiter des Service-Centers', grant: 'Bearbeitung erlauben', revoke: 'Bearbeitung entziehen', save: 'Speichern', cancel: 'Abbrechen', network: { tailscale: 'Tailscale', lan: 'Lokales Netzwerk', public: 'Öffentlich', local: 'Dieses Gerät' }, health: { untested: 'Nicht geprüft', unapproved: 'Nicht genehmigt', disabled: 'Prüfung aus', healthy: 'Server antwortet', http_error: 'HTTP-Fehler', redirected: 'Weiterleitung', timeout: 'Zeitüberschreitung', unreachable: 'Nicht erreichbar', blocked: 'Blockiert', busy: 'Prüfung begrenzt' } }),
  pt: localized({ title: 'Central de serviços', subtitle: 'Ferramentas e serviços web registrados em um só lugar.', reachability: 'O acesso depende da rede do dispositivo. A verificação do servidor não confirma o acesso pelo navegador.', refresh: 'Atualizar', export: 'Exportar JSON', import: 'Importar JSON', add: 'Adicionar serviço', edit: 'Editar', delete: 'Excluir', favorite: 'Adicionar aos favoritos', unfavorite: 'Remover dos favoritos', favorites: 'Favoritos', search: 'Buscar nome, categoria ou tag', categoryFilter: 'Categoria', allCategories: 'Todas as categorias', noMatches: 'Nenhum serviço encontrado.', empty: 'Nenhum serviço registrado.', loading: 'Carregando…', check: 'Verificar servidor', approve: 'Aprovar verificação', revokeApproval: 'Revogar aprovação', permissions: 'Editores', permissionsTitle: 'Editores da central', grant: 'Conceder edição', revoke: 'Revogar edição', save: 'Salvar', cancel: 'Cancelar', network: { tailscale: 'Tailscale', lan: 'Rede local', public: 'Pública', local: 'Este dispositivo' }, health: { untested: 'Não verificado', unapproved: 'Não aprovado', disabled: 'Verificação desativada', healthy: 'Servidor responde', http_error: 'Erro HTTP', redirected: 'Redirecionamento', timeout: 'Tempo esgotado', unreachable: 'Inacessível', blocked: 'Bloqueado', busy: 'Verificação limitada' } }),
  ru: localized({ title: 'Центр сервисов', subtitle: 'Зарегистрированные инструменты и веб-сервисы в одном месте.', reachability: 'Доступ зависит от сети устройства. Проверка сервера не гарантирует доступ из браузера.', refresh: 'Обновить', export: 'Экспорт JSON', import: 'Импорт JSON', add: 'Добавить сервис', edit: 'Изменить', delete: 'Удалить', favorite: 'В избранное', unfavorite: 'Убрать из избранного', favorites: 'Избранное', search: 'Поиск по названию, категории или тегу', categoryFilter: 'Категория', allCategories: 'Все категории', noMatches: 'Совпадений нет.', empty: 'Сервисы не зарегистрированы.', loading: 'Загрузка…', check: 'Проверить сервер', approve: 'Разрешить проверку', revokeApproval: 'Отозвать разрешение', permissions: 'Редакторы', permissionsTitle: 'Редакторы центра', grant: 'Выдать доступ', revoke: 'Отозвать доступ', save: 'Сохранить', cancel: 'Отмена', network: { tailscale: 'Tailscale', lan: 'Локальная сеть', public: 'Публичная', local: 'Это устройство' }, health: { untested: 'Не проверен', unapproved: 'Не разрешено', disabled: 'Проверка выключена', healthy: 'Сервер отвечает', http_error: 'Ошибка HTTP', redirected: 'Перенаправление', timeout: 'Тайм-аут', unreachable: 'Недоступен', blocked: 'Заблокирован', busy: 'Проверка ограничена' } }),
  ar: localized({ title: 'مركز الخدمات', subtitle: 'الأدوات وخدمات الويب المسجلة في مكان واحد.', reachability: 'يعتمد الوصول على شبكة جهازك. فحص الخادم لا يثبت إمكانية الوصول من المتصفح.', refresh: 'تحديث', export: 'تصدير JSON', import: 'استيراد JSON', add: 'إضافة خدمة', edit: 'تعديل', delete: 'حذف', favorite: 'إضافة للمفضلة', unfavorite: 'إزالة من المفضلة', favorites: 'المفضلة', search: 'البحث بالاسم أو الفئة أو الوسم', categoryFilter: 'الفئة', allCategories: 'كل الفئات', noMatches: 'لا توجد خدمات مطابقة.', empty: 'لا توجد خدمات مسجلة.', loading: 'جارٍ التحميل…', check: 'فحص الخادم', approve: 'الموافقة على الفحص', revokeApproval: 'سحب الموافقة', permissions: 'المحررون', permissionsTitle: 'محررو مركز الخدمات', grant: 'منح صلاحية التحرير', revoke: 'سحب صلاحية التحرير', save: 'حفظ', cancel: 'إلغاء', network: { tailscale: 'Tailscale', lan: 'الشبكة المحلية', public: 'عامة', local: 'هذا الجهاز' }, health: { untested: 'لم يُفحص', unapproved: 'غير معتمد', disabled: 'الفحص متوقف', healthy: 'الخادم يستجيب', http_error: 'خطأ HTTP', redirected: 'إعادة توجيه', timeout: 'انتهت المهلة', unreachable: 'تعذر الوصول', blocked: 'محظور', busy: 'الفحص محدود' } }),
}
