// Module-owned v2 copy. Every supported locale supplies the new directory,
// entrance and information-panel vocabulary rather than inheriting English.
const zhTW = {
  open: '開啟', info: '資訊', close: '關閉', legend: '標示說明', overview: '概覽', deployment: '部署位置', unknownLocation: '未設定部署位置', uncategorized: '未分類', allDeployments: '所有位置', allNetworks: '所有網路', entrances: '服務入口', entrance: '入口', defaultEntry: '預設', selectedEntry: '已選', unavailable: '無法開啟', loginRequired: '需登入', loginLabel: '登入要求', backendCheck: '後端檢查', management: '管理服務', localWarning: '本機位址指部署主機，不是目前瀏覽裝置。',
  legendLogin: '登入要求由編輯者聲明；系統不會驗證認證狀態。', legendHealth: '未檢查、已停用或未核准均非已驗證結果。後端檢查不代表瀏覽器可連線。',
  manageOrganization: '管理分類與位置', categories: '分類', deployments: '部署位置', addGroup: '新增', reassignHint: '{count} 個服務使用此項目。請選替代項目或明確設為無。', chooseTarget: '選擇重新指派', deleteGroupConfirm: '在同一筆目錄修訂中刪除並重新指派？', confirmDelete: '刪除並指派', moveUp: '上移', moveDown: '下移', removeEntrance: '移除', addEntrance: '新增入口', entranceId: '入口 ID', entranceLabel: '入口名稱', setDefault: '預設入口', entranceHint: '最多八個入口。移除預設入口前須先選新的預設。', invalidEntrances: '每個入口都需名稱與安全網址，並指定有效預設。', importEntities: '新增 {categories} 個分類、{nodes} 個位置',
  networkLocal: '主機限定', healthStale: '先前結果（已過期）',
  login: { unknown: '登入狀態未知', required: '需登入（編輯者聲明）', none: '無需登入（編輯者聲明）' },
  legendNetwork: { local: '僅部署主機可開啟，不代表你的手機可連線。', lan: '瀏覽裝置須連上相同區域網路。', tailscale: '瀏覽裝置須能連上 Tailscale。', public: '公開位址；實際連線尚未驗證。' },
}

type Sc02Labels = typeof zhTW
export const sc02Localized: Record<'zh-TW' | 'zh' | 'ja' | 'ko' | 'fr' | 'es' | 'de' | 'pt' | 'ru' | 'ar', Sc02Labels> = {
  'zh-TW': zhTW,
  zh: {
    open: '打开', info: '信息', close: '关闭', legend: '标识说明', overview: '概览', deployment: '部署位置', unknownLocation: '未设置部署位置', uncategorized: '未分类', allDeployments: '所有位置', allNetworks: '所有网络', entrances: '服务入口', entrance: '入口', defaultEntry: '默认', selectedEntry: '已选', unavailable: '无法打开', loginRequired: '需登录', loginLabel: '登录要求', backendCheck: '后端检查', management: '管理服务', localWarning: '本机地址指部署主机，不是当前浏览设备。',
    legendLogin: '登录要求由编辑者声明；系统不会验证认证状态。', legendHealth: '未检查、已停用或未批准均非已验证结果。后端检查不代表浏览器可连接。',
    manageOrganization: '管理分类和位置', categories: '分类', deployments: '部署位置', addGroup: '添加', reassignHint: '{count} 个服务使用此项。请选择替代项或明确设为无。', chooseTarget: '选择重新分配', deleteGroupConfirm: '在同一次目录修订中删除并重新分配？', confirmDelete: '删除并分配', moveUp: '上移', moveDown: '下移', removeEntrance: '移除', addEntrance: '添加入口', entranceId: '入口 ID', entranceLabel: '入口名称', setDefault: '默认入口', entranceHint: '最多八个入口。移除默认入口前须先选择新的默认项。', invalidEntrances: '每个入口都需要名称和安全网址，并指定有效默认项。', importEntities: '新增 {categories} 个分类、{nodes} 个位置',
    networkLocal: '仅限主机', healthStale: '先前结果（已过期）', legendNetwork: { local: '仅部署主机可打开，不代表手机可以连接。', lan: '浏览设备须连接同一局域网。', tailscale: '浏览设备须能连接 Tailscale。', public: '公开地址；实际连接未经验证。' },
    login: { unknown: '登录状态未知', required: '需登录（编辑者声明）', none: '无需登录（编辑者声明）' },
  },
  ja: {
    open: '開く', info: '詳細', close: '閉じる', legend: '表示の説明', overview: '概要', deployment: '配置先', unknownLocation: '配置先未設定', uncategorized: '未分類', allDeployments: 'すべての配置先', allNetworks: 'すべてのネットワーク', entrances: '入口', entrance: '入口', defaultEntry: '既定', selectedEntry: '選択中', unavailable: '利用不可', loginRequired: 'ログインが必要', loginLabel: 'ログイン要件', backendCheck: 'サーバー検査', management: 'サービス管理', localWarning: 'localhost は配置先ホストを指し、閲覧中の端末ではありません。',
    legendLogin: 'ログイン要件は編集者の申告です。認証状態は検証しません。', legendHealth: '未検査・無効・未承認は検証済みではありません。サーバー検査はブラウザーからの接続を保証しません。',
    manageOrganization: 'カテゴリと配置先を管理', categories: 'カテゴリ', deployments: '配置先', addGroup: '追加', reassignHint: '{count} 件のサービスが使用中です。移動先または「なし」を明示してください。', chooseTarget: '移動先を選択', deleteGroupConfirm: '同じリビジョンで削除と再割り当てを行いますか？', confirmDelete: '削除して再割り当て', moveUp: '上へ', moveDown: '下へ', removeEntrance: '削除', addEntrance: '入口を追加', entranceId: '入口 ID', entranceLabel: '表示名', setDefault: '既定の入口', entranceHint: '最大8件。既定の入口を削除する前に別の入口を選択してください。', invalidEntrances: 'すべての入口に名前と安全な URL を指定し、既定の入口を選択してください。', importEntities: '新規カテゴリ {categories} 件、配置先 {nodes} 件',
    networkLocal: '配置先ホストのみ', healthStale: '以前の結果（期限切れ）', legendNetwork: { local: '配置先ホストのみ。閲覧中の端末からの接続は保証されません。', lan: '閲覧端末を同じ LAN に接続してください。', tailscale: '閲覧端末に Tailscale 接続が必要です。', public: '公開アドレス。実際の接続は未検証です。' },
    login: { unknown: 'ログイン状況は不明', required: 'ログインが必要（編集者の申告）', none: 'ログイン不要（編集者の申告）' },
  },
  ko: {
    open: '열기', info: '정보', close: '닫기', legend: '표시 안내', overview: '개요', deployment: '배포 위치', unknownLocation: '위치 미설정', uncategorized: '미분류', allDeployments: '모든 위치', allNetworks: '모든 네트워크', entrances: '접속 경로', entrance: '접속 경로', defaultEntry: '기본', selectedEntry: '선택됨', unavailable: '사용 불가', loginRequired: '로그인 필요', loginLabel: '로그인 요구', backendCheck: '서버 검사', management: '서비스 관리', localWarning: 'localhost는 배포 호스트를 뜻하며 현재 보는 기기가 아닙니다.',
    legendLogin: '로그인 요구는 편집자가 선언합니다. 인증 상태는 검사하지 않습니다.', legendHealth: '미검사·비활성·미승인은 확인된 결과가 아닙니다. 서버 검사는 브라우저 접속을 보장하지 않습니다.',
    manageOrganization: '분류와 위치 관리', categories: '분류', deployments: '배포 위치', addGroup: '추가', reassignHint: '{count}개 서비스가 사용 중입니다. 다른 항목이나 없음으로 명시적으로 재배정하세요.', chooseTarget: '재배정 대상 선택', deleteGroupConfirm: '한 번의 수정으로 삭제하고 재배정하시겠습니까?', confirmDelete: '삭제 및 재배정', moveUp: '위로', moveDown: '아래로', removeEntrance: '제거', addEntrance: '경로 추가', entranceId: '경로 ID', entranceLabel: '표시 이름', setDefault: '기본 경로', entranceHint: '최대 8개. 기본 경로를 지우기 전에 다른 기본값을 선택하세요.', invalidEntrances: '모든 경로에 이름과 안전한 URL을 입력하고 유효한 기본값을 선택하세요.', importEntities: '새 분류 {categories}개, 위치 {nodes}개',
    networkLocal: '배포 호스트 전용', healthStale: '이전 결과(만료)', legendNetwork: { local: '배포 호스트에서만 접근할 수 있으며 현재 기기와 다릅니다.', lan: '보는 기기가 같은 LAN에 있어야 합니다.', tailscale: '보는 기기에 Tailscale 연결이 필요합니다.', public: '공개 주소지만 실제 접속은 확인되지 않았습니다.' },
    login: { unknown: '로그인 상태 알 수 없음', required: '로그인 필요(편집자 선언)', none: '로그인 불필요(편집자 선언)' },
  },
  fr: {
    open: 'Ouvrir', info: 'Infos', close: 'Fermer', legend: 'Légende', overview: 'Aperçu', deployment: 'Emplacement', unknownLocation: 'Emplacement non défini', uncategorized: 'Sans catégorie', allDeployments: 'Tous les emplacements', allNetworks: 'Tous les réseaux', entrances: 'Accès', entrance: 'Accès', defaultEntry: 'Par défaut', selectedEntry: 'Sélectionné', unavailable: 'Indisponible', loginRequired: 'Connexion requise', loginLabel: 'Connexion déclarée', backendCheck: 'Contrôle serveur', management: 'Gérer le service', localWarning: 'localhost désigne l’hôte de déploiement, pas votre appareil.',
    legendLogin: 'L’éditeur déclare la connexion requise ; aucune authentification n’est vérifiée.', legendHealth: 'Non testé, désactivé ou non approuvé ne constitue pas un résultat vérifié. Le contrôle serveur ne prouve pas l’accès du navigateur.',
    manageOrganization: 'Gérer catégories et emplacements', categories: 'Catégories', deployments: 'Emplacements', addGroup: 'Ajouter', reassignHint: '{count} services utilisent cet élément. Choisissez un remplacement ou explicitement aucun.', chooseTarget: 'Choisir une réaffectation', deleteGroupConfirm: 'Supprimer et réaffecter dans la même révision ?', confirmDelete: 'Supprimer et réaffecter', moveUp: 'Monter', moveDown: 'Descendre', removeEntrance: 'Retirer', addEntrance: 'Ajouter un accès', entranceId: 'ID d’accès', entranceLabel: 'Libellé', setDefault: 'Accès par défaut', entranceHint: 'Huit accès maximum. Choisissez un autre défaut avant de supprimer celui-ci.', invalidEntrances: 'Chaque accès doit avoir un libellé et une URL sûre, avec un défaut valide.', importEntities: '{categories} nouvelles catégories, {nodes} nouveaux emplacements',
    networkLocal: 'Hôte uniquement', healthStale: 'Ancien résultat (périmé)', legendNetwork: { local: 'Accessible uniquement sur l’hôte de déploiement, pas forcément sur votre appareil.', lan: 'Votre appareil doit être sur le même réseau local.', tailscale: 'Votre appareil doit avoir accès à Tailscale.', public: 'Adresse publique ; l’accès réel n’a pas été vérifié.' },
    login: { unknown: 'Connexion inconnue', required: 'Connexion requise (déclarée)', none: 'Aucune connexion (déclarée)' },
  },
  es: {
    open: 'Abrir', info: 'Información', close: 'Cerrar', legend: 'Guía de estados', overview: 'Resumen', deployment: 'Ubicación', unknownLocation: 'Ubicación sin definir', uncategorized: 'Sin categoría', allDeployments: 'Todas las ubicaciones', allNetworks: 'Todas las redes', entrances: 'Accesos', entrance: 'Acceso', defaultEntry: 'Predeterminado', selectedEntry: 'Seleccionado', unavailable: 'No disponible', loginRequired: 'Requiere inicio de sesión', loginLabel: 'Inicio de sesión declarado', backendCheck: 'Comprobación del servidor', management: 'Gestionar servicio', localWarning: 'localhost se refiere al servidor de despliegue, no al dispositivo desde el que navegas.',
    legendLogin: 'El editor declara si se requiere inicio de sesión. No verificamos la autenticación.', legendHealth: 'Sin probar, desactivado o no aprobado no es un resultado verificado. La prueba del servidor no confirma el acceso del navegador.',
    manageOrganization: 'Gestionar categorías y ubicaciones', categories: 'Categorías', deployments: 'Ubicaciones', addGroup: 'Añadir', reassignHint: '{count} servicios usan este elemento. Elige otro destino o ninguno de forma explícita.', chooseTarget: 'Elegir destino', deleteGroupConfirm: '¿Eliminar y reasignar en la misma revisión?', confirmDelete: 'Eliminar y reasignar', moveUp: 'Subir', moveDown: 'Bajar', removeEntrance: 'Quitar', addEntrance: 'Añadir acceso', entranceId: 'ID de acceso', entranceLabel: 'Nombre', setDefault: 'Acceso predeterminado', entranceHint: 'Hasta ocho accesos. Elige otro predeterminado antes de eliminarlo.', invalidEntrances: 'Cada acceso necesita nombre y URL segura, además de un predeterminado válido.', importEntities: '{categories} categorías nuevas, {nodes} ubicaciones nuevas',
    networkLocal: 'Solo servidor', healthStale: 'Resultado anterior (caducado)', legendNetwork: { local: 'Solo disponible en el servidor de despliegue, no necesariamente en tu dispositivo.', lan: 'Tu dispositivo debe estar en la misma red local.', tailscale: 'Tu dispositivo necesita acceso a Tailscale.', public: 'Dirección pública; no se ha verificado el acceso real.' },
    login: { unknown: 'Inicio de sesión desconocido', required: 'Requiere inicio de sesión (declarado)', none: 'No requiere inicio de sesión (declarado)' },
  },
  de: {
    open: 'Öffnen', info: 'Info', close: 'Schließen', legend: 'Kennzeichnungen', overview: 'Übersicht', deployment: 'Standort', unknownLocation: 'Standort nicht angegeben', uncategorized: 'Ohne Kategorie', allDeployments: 'Alle Standorte', allNetworks: 'Alle Netzwerke', entrances: 'Zugänge', entrance: 'Zugang', defaultEntry: 'Standard', selectedEntry: 'Ausgewählt', unavailable: 'Nicht verfügbar', loginRequired: 'Anmeldung nötig', loginLabel: 'Anmeldung laut Angabe', backendCheck: 'Serverprüfung', management: 'Dienst verwalten', localWarning: 'localhost bezeichnet den Bereitstellungshost, nicht dein Anzeigegerät.',
    legendLogin: 'Die Anmeldeanforderung ist eine Angabe der Redaktion. Die Authentifizierung wird nicht geprüft.', legendHealth: 'Ungeprüft, deaktiviert oder nicht genehmigt ist kein verifiziertes Ergebnis. Die Serverprüfung belegt keinen Browserzugriff.',
    manageOrganization: 'Kategorien und Standorte verwalten', categories: 'Kategorien', deployments: 'Standorte', addGroup: 'Hinzufügen', reassignHint: '{count} Dienste verwenden diesen Eintrag. Ersatz oder ausdrücklich „keinen“ wählen.', chooseTarget: 'Neuzuordnung wählen', deleteGroupConfirm: 'In derselben Revision löschen und neu zuordnen?', confirmDelete: 'Löschen und zuordnen', moveUp: 'Nach oben', moveDown: 'Nach unten', removeEntrance: 'Entfernen', addEntrance: 'Zugang hinzufügen', entranceId: 'Zugangs-ID', entranceLabel: 'Bezeichnung', setDefault: 'Standardzugang', entranceHint: 'Bis zu acht Zugänge. Vor dem Entfernen des Standards einen neuen wählen.', invalidEntrances: 'Jeder Zugang braucht einen Namen und eine sichere URL sowie einen gültigen Standard.', importEntities: '{categories} neue Kategorien, {nodes} neue Standorte',
    networkLocal: 'Nur Host', healthStale: 'Vorheriges Ergebnis (veraltet)', legendNetwork: { local: 'Nur auf dem Bereitstellungshost erreichbar, nicht unbedingt auf deinem Gerät.', lan: 'Dein Gerät muss im selben lokalen Netzwerk sein.', tailscale: 'Dein Gerät braucht Tailscale-Zugang.', public: 'Öffentliche Adresse; tatsächlicher Zugriff nicht geprüft.' },
    login: { unknown: 'Anmeldestatus unbekannt', required: 'Anmeldung nötig (deklariert)', none: 'Keine Anmeldung (deklariert)' },
  },
  pt: {
    open: 'Abrir', info: 'Informações', close: 'Fechar', legend: 'Guia de estados', overview: 'Resumo', deployment: 'Local', unknownLocation: 'Local não definido', uncategorized: 'Sem categoria', allDeployments: 'Todos os locais', allNetworks: 'Todas as redes', entrances: 'Acessos', entrance: 'Acesso', defaultEntry: 'Padrão', selectedEntry: 'Selecionado', unavailable: 'Indisponível', loginRequired: 'Login necessário', loginLabel: 'Login declarado', backendCheck: 'Verificação do servidor', management: 'Gerenciar serviço', localWarning: 'localhost indica o host de implantação, não o dispositivo que você está usando.',
    legendLogin: 'O editor declara a necessidade de login. A autenticação não é verificada.', legendHealth: 'Não testado, desativado ou não aprovado não é um resultado verificado. A verificação do servidor não confirma o acesso pelo navegador.',
    manageOrganization: 'Gerenciar categorias e locais', categories: 'Categorias', deployments: 'Locais', addGroup: 'Adicionar', reassignHint: '{count} serviços usam este item. Escolha outro destino ou nenhum explicitamente.', chooseTarget: 'Escolher destino', deleteGroupConfirm: 'Excluir e reatribuir na mesma revisão?', confirmDelete: 'Excluir e reatribuir', moveUp: 'Subir', moveDown: 'Descer', removeEntrance: 'Remover', addEntrance: 'Adicionar acesso', entranceId: 'ID do acesso', entranceLabel: 'Nome', setDefault: 'Acesso padrão', entranceHint: 'Até oito acessos. Escolha outro padrão antes de removê-lo.', invalidEntrances: 'Cada acesso precisa de nome e URL segura, com um padrão válido.', importEntities: '{categories} novas categorias, {nodes} novos locais',
    networkLocal: 'Somente host', healthStale: 'Resultado anterior (expirado)', legendNetwork: { local: 'Acessível só no host de implantação, não necessariamente no seu aparelho.', lan: 'Seu aparelho deve estar na mesma rede local.', tailscale: 'Seu aparelho precisa de acesso ao Tailscale.', public: 'Endereço público; acesso real não verificado.' },
    login: { unknown: 'Login desconhecido', required: 'Login necessário (declarado)', none: 'Sem login (declarado)' },
  },
  ru: {
    open: 'Открыть', info: 'Сведения', close: 'Закрыть', legend: 'Обозначения', overview: 'Обзор', deployment: 'Расположение', unknownLocation: 'Расположение не задано', uncategorized: 'Без категории', allDeployments: 'Все расположения', allNetworks: 'Все сети', entrances: 'Адреса доступа', entrance: 'Адрес', defaultEntry: 'По умолчанию', selectedEntry: 'Выбран', unavailable: 'Недоступно', loginRequired: 'Нужен вход', loginLabel: 'Заявленный вход', backendCheck: 'Проверка сервера', management: 'Управление сервисом', localWarning: 'localhost обозначает хост размещения, а не ваше устройство просмотра.',
    legendLogin: 'Требование входа указывает редактор. Мы не проверяем авторизацию.', legendHealth: 'Отсутствие проверки, отключение или отсутствие разрешения не означает подтверждённый результат. Проверка сервера не гарантирует доступ из браузера.',
    manageOrganization: 'Категории и расположения', categories: 'Категории', deployments: 'Расположения', addGroup: 'Добавить', reassignHint: 'Этот пункт используют {count} сервисов. Выберите замену или явно укажите «нет».', chooseTarget: 'Выбрать замену', deleteGroupConfirm: 'Удалить и переназначить в одной ревизии?', confirmDelete: 'Удалить и переназначить', moveUp: 'Выше', moveDown: 'Ниже', removeEntrance: 'Убрать', addEntrance: 'Добавить адрес', entranceId: 'ID адреса', entranceLabel: 'Название', setDefault: 'Адрес по умолчанию', entranceHint: 'Не более восьми адресов. Перед удалением основного выберите другой.', invalidEntrances: 'У каждого адреса должны быть название, безопасный URL и действующий адрес по умолчанию.', importEntities: 'Новые категории: {categories}; расположения: {nodes}',
    networkLocal: 'Только хост', healthStale: 'Старый результат (устарел)', legendNetwork: { local: 'Доступно только на хосте размещения, не обязательно на вашем устройстве.', lan: 'Устройство просмотра должно быть в той же локальной сети.', tailscale: 'Устройству просмотра нужен доступ к Tailscale.', public: 'Публичный адрес; фактический доступ не проверен.' },
    login: { unknown: 'Требование входа неизвестно', required: 'Нужен вход (указано редактором)', none: 'Вход не нужен (указано редактором)' },
  },
  ar: {
    open: 'فتح', info: 'معلومات', close: 'إغلاق', legend: 'دليل العلامات', overview: 'نظرة عامة', deployment: 'موقع التشغيل', unknownLocation: 'لم يحدد موقع التشغيل', uncategorized: 'غير مصنف', allDeployments: 'كل المواقع', allNetworks: 'كل الشبكات', entrances: 'مداخل الخدمة', entrance: 'المدخل', defaultEntry: 'الافتراضي', selectedEntry: 'المحدد', unavailable: 'غير متاح', loginRequired: 'يلزم تسجيل الدخول', loginLabel: 'متطلبات الدخول المعلنة', backendCheck: 'فحص الخادم', management: 'إدارة الخدمة', localWarning: 'يشير localhost إلى خادم التشغيل، وليس جهازك الذي تعرض منه الصفحة.',
    legendLogin: 'يعلن المحرر متطلبات الدخول؛ لا نتحقق من المصادقة.', legendHealth: 'عدم الفحص أو التعطيل أو غياب الموافقة لا يعني نتيجة موثقة. فحص الخادم لا يثبت إمكانية الوصول من المتصفح.',
    manageOrganization: 'إدارة التصنيفات والمواقع', categories: 'التصنيفات', deployments: 'مواقع التشغيل', addGroup: 'إضافة', reassignHint: 'تستخدم {count} خدمات هذا العنصر. اختر بديلاً أو حدد «لا شيء» صراحةً.', chooseTarget: 'اختر إعادة التعيين', deleteGroupConfirm: 'حذف وإعادة تعيين في مراجعة واحدة؟', confirmDelete: 'حذف وإعادة تعيين', moveUp: 'تحريك للأعلى', moveDown: 'تحريك للأسفل', removeEntrance: 'إزالة', addEntrance: 'إضافة مدخل', entranceId: 'معرّف المدخل', entranceLabel: 'الاسم', setDefault: 'المدخل الافتراضي', entranceHint: 'حتى ثمانية مداخل. اختر مدخلاً افتراضياً بديلاً قبل حذف الحالي.', invalidEntrances: 'أدخل اسماً ورابطاً آمناً لكل مدخل واختر مدخلاً افتراضياً صالحاً.', importEntities: 'تصنيفات جديدة: {categories}، مواقع جديدة: {nodes}',
    networkLocal: 'لخادم التشغيل فقط', healthStale: 'نتيجة سابقة (منتهية)', legendNetwork: { local: 'متاح على خادم التشغيل فقط، وليس بالضرورة على جهازك.', lan: 'يجب أن يتصل جهاز العرض بالشبكة المحلية نفسها.', tailscale: 'يحتاج جهاز العرض إلى اتصال Tailscale.', public: 'عنوان عام؛ لم نتحقق من الوصول الفعلي.' },
    login: { unknown: 'حالة تسجيل الدخول غير معروفة', required: 'يلزم تسجيل الدخول (بحسب المحرر)', none: 'لا يلزم تسجيل الدخول (بحسب المحرر)' },
  },
}
