const en = {
  title: 'Personal assistant', subtitle: 'One central assistant. Files stay on the device you select.', workbench: 'Workbench', personal: 'Personal', chooseMode: 'Choose your mode',
  central: 'Central conversation', connect: 'Connect account', notConnected: 'No central connection. Replies appear after your account, profile and session are verified.', connected: 'Connected',
  origin: 'Central origin', username: 'Username', password: 'Password', profile: 'Profile', session: 'Session ID', send: 'Send', historyEmpty: 'No messages in this session.',
  files: 'Files on your devices', chooseFolder: 'Choose a folder', empty: 'No workspace selected. Use the desktop folder picker to grant access.', target: 'Device / workspace', refresh: 'Refresh',
  search: 'Search', path: 'Relative file path', content: 'File contents', create: 'Create', overwrite: 'Overwrite', remove: 'Delete', cancel: 'Cancel', confirm: 'Confirm deletion',
  restore: 'Restore last deletion', revoke: 'Revoke access', more: 'Load more', status: 'Check operation status', truncated: 'Partial read. Overwrite is disabled.', readonly: 'Access is limited to the permissions below.',
  hostname: 'Hostname', device: 'Device ID', workspace: 'Workspace ID', hash: 'Expected SHA-256', nativeOnly: 'Folder registration requires the local desktop picker.',
}
type Messages = typeof en
const localized = (value: Partial<Messages>): Messages => ({ ...en, ...value })
export const personalAgentMessages: Record<string, Messages> = {
  en,
  'zh-TW': localized({ title: '個人助理', subtitle: '連到同一位中央助理；檔案留在你選擇的裝置。', workbench: '工作台', personal: '個人', chooseMode: '選擇使用模式', central: '中央對話', connect: '連接帳號', notConnected: '尚未連接中央。驗證帳號、profile 與 session 後才會顯示回覆。', connected: '已連接', origin: '中央 origin', username: '帳號', password: '密碼', profile: 'Profile', session: 'Session ID', send: '傳送', historyEmpty: '此對話尚無訊息。', files: '裝置上的檔案', chooseFolder: '選擇資料夾', empty: '尚未選擇工作區。請用桌面資料夾選擇器授權。', target: '裝置／工作區', refresh: '重新整理', search: '搜尋', path: '檔案相對路徑', content: '檔案內容', create: '新增', overwrite: '覆寫', remove: '刪除', cancel: '取消', confirm: '確認刪除', restore: '還原上次刪除', revoke: '撤銷權限', more: '載入更多', status: '查詢操作狀態', truncated: '僅讀取部分內容；已停用覆寫。', readonly: '僅可執行下方已授權的操作。', hostname: '主機名稱', device: '裝置 ID', workspace: '工作區 ID', hash: '預期 SHA-256', nativeOnly: '登記工作區需要本機桌面選擇器。' }),
  zh: localized({ title: '个人助理', subtitle: '连接同一位中央助理；文件留在所选设备。', workbench: '工作台', personal: '个人', chooseMode: '选择模式', central: '中央对话', connect: '连接账号', notConnected: '尚未连接中央。验证账号、profile 和 session 后才显示回复。', connected: '已连接', username: '账号', password: '密码', send: '发送', files: '设备文件', chooseFolder: '选择文件夹', empty: '尚未选择工作区。请用桌面选择器授权。', target: '设备／工作区', refresh: '刷新', search: '搜索', path: '相对文件路径', content: '文件内容', create: '新建', overwrite: '覆盖', remove: '删除', cancel: '取消', confirm: '确认删除', restore: '恢复上次删除', revoke: '撤销权限', more: '加载更多', status: '查询操作状态', hostname: '主机名称', device: '设备 ID', workspace: '工作区 ID' }),
  ja: localized({ title: '個人アシスタント', workbench: 'ワークベンチ', personal: '個人', chooseMode: 'モードを選択', central: '中央の会話', connect: 'アカウントを接続', notConnected: '未接続です。アカウントとセッションの確認が必要です。', connected: '接続済み', username: 'ユーザー名', password: 'パスワード', send: '送信', files: '端末のファイル', chooseFolder: 'フォルダーを選択', empty: 'ワークスペース未選択。', target: '端末／ワークスペース', refresh: '更新', search: '検索', path: '相対パス', content: '内容', create: '作成', overwrite: '上書き', remove: '削除', cancel: 'キャンセル', confirm: '削除を確認', restore: '復元', revoke: '権限を撤回', more: 'さらに表示', status: '状態を確認' }),
  ko: localized({ title: '개인 비서', workbench: '워크벤치', personal: '개인', chooseMode: '모드 선택', central: '중앙 대화', connect: '계정 연결', notConnected: '연결되지 않았습니다. 계정과 세션 확인이 필요합니다.', connected: '연결됨', username: '사용자 이름', password: '비밀번호', send: '보내기', files: '기기 파일', chooseFolder: '폴더 선택', empty: '선택된 작업 공간이 없습니다.', target: '기기 / 작업 공간', refresh: '새로고침', search: '검색', path: '상대 경로', content: '파일 내용', create: '만들기', overwrite: '덮어쓰기', remove: '삭제', cancel: '취소', confirm: '삭제 확인', restore: '복원', revoke: '접근 권한 회수', more: '더 보기', status: '상태 확인' }),
  fr: localized({ title: 'Assistant personnel', workbench: 'Atelier', personal: 'Personnel', chooseMode: 'Choisir le mode', central: 'Conversation centrale', connect: 'Connecter le compte', notConnected: 'Non connecté. Vérifiez le compte et la session.', connected: 'Connecté', username: 'Identifiant', password: 'Mot de passe', send: 'Envoyer', files: 'Fichiers des appareils', chooseFolder: 'Choisir un dossier', empty: 'Aucun espace sélectionné.', target: 'Appareil / espace', refresh: 'Actualiser', search: 'Rechercher', path: 'Chemin relatif', content: 'Contenu', create: 'Créer', overwrite: 'Écraser', remove: 'Supprimer', cancel: 'Annuler', confirm: 'Confirmer la suppression', restore: 'Restaurer', revoke: 'Révoquer', more: 'Afficher plus', status: 'Vérifier le statut' }),
  es: localized({ title: 'Asistente personal', workbench: 'Banco de trabajo', personal: 'Personal', chooseMode: 'Elegir modo', central: 'Conversación central', connect: 'Conectar cuenta', notConnected: 'Sin conexión. Verifica la cuenta y la sesión.', connected: 'Conectado', username: 'Usuario', password: 'Contraseña', send: 'Enviar', files: 'Archivos de dispositivos', chooseFolder: 'Elegir carpeta', empty: 'No hay espacio seleccionado.', target: 'Dispositivo / espacio', refresh: 'Actualizar', search: 'Buscar', path: 'Ruta relativa', content: 'Contenido', create: 'Crear', overwrite: 'Sobrescribir', remove: 'Eliminar', cancel: 'Cancelar', confirm: 'Confirmar eliminación', restore: 'Restaurar', revoke: 'Revocar', more: 'Ver más', status: 'Verificar estado' }),
  de: localized({ title: 'Persönlicher Assistent', workbench: 'Arbeitsbereich', personal: 'Persönlich', chooseMode: 'Modus wählen', central: 'Zentrales Gespräch', connect: 'Konto verbinden', notConnected: 'Nicht verbunden. Konto und Sitzung prüfen.', connected: 'Verbunden', username: 'Benutzername', password: 'Passwort', send: 'Senden', files: 'Gerätedateien', chooseFolder: 'Ordner wählen', empty: 'Kein Arbeitsbereich gewählt.', target: 'Gerät / Arbeitsbereich', refresh: 'Aktualisieren', search: 'Suchen', path: 'Relativer Pfad', content: 'Inhalt', create: 'Erstellen', overwrite: 'Überschreiben', remove: 'Löschen', cancel: 'Abbrechen', confirm: 'Löschen bestätigen', restore: 'Wiederherstellen', revoke: 'Zugriff entziehen', more: 'Mehr laden', status: 'Status prüfen' }),
  pt: localized({ title: 'Assistente pessoal', workbench: 'Área de trabalho', personal: 'Pessoal', chooseMode: 'Escolher modo', central: 'Conversa central', connect: 'Conectar conta', notConnected: 'Sem conexão. Verifique a conta e a sessão.', connected: 'Conectado', username: 'Usuário', password: 'Senha', send: 'Enviar', files: 'Arquivos dos dispositivos', chooseFolder: 'Escolher pasta', empty: 'Nenhum espaço selecionado.', target: 'Dispositivo / espaço', refresh: 'Atualizar', search: 'Buscar', path: 'Caminho relativo', content: 'Conteúdo', create: 'Criar', overwrite: 'Sobrescrever', remove: 'Excluir', cancel: 'Cancelar', confirm: 'Confirmar exclusão', restore: 'Restaurar', revoke: 'Revogar', more: 'Carregar mais', status: 'Consultar status' }),
  ru: localized({ title: 'Личный помощник', workbench: 'Рабочая область', personal: 'Личный', chooseMode: 'Выберите режим', central: 'Центральный диалог', connect: 'Подключить аккаунт', notConnected: 'Нет подключения. Проверьте аккаунт и сессию.', connected: 'Подключено', username: 'Имя пользователя', password: 'Пароль', send: 'Отправить', files: 'Файлы устройств', chooseFolder: 'Выбрать папку', empty: 'Рабочая область не выбрана.', target: 'Устройство / область', refresh: 'Обновить', search: 'Поиск', path: 'Относительный путь', content: 'Содержимое', create: 'Создать', overwrite: 'Перезаписать', remove: 'Удалить', cancel: 'Отмена', confirm: 'Подтвердить удаление', restore: 'Восстановить', revoke: 'Отозвать доступ', more: 'Загрузить ещё', status: 'Проверить статус' }),
  ar: localized({ title: 'المساعد الشخصي', workbench: 'مساحة العمل', personal: 'شخصي', chooseMode: 'اختر الوضع', central: 'المحادثة المركزية', connect: 'ربط الحساب', notConnected: 'غير متصل. تحقق من الحساب والجلسة.', connected: 'متصل', username: 'اسم المستخدم', password: 'كلمة المرور', send: 'إرسال', files: 'ملفات الأجهزة', chooseFolder: 'اختر مجلداً', empty: 'لم يتم اختيار مساحة عمل.', target: 'الجهاز / مساحة العمل', refresh: 'تحديث', search: 'بحث', path: 'المسار النسبي', content: 'المحتوى', create: 'إنشاء', overwrite: 'استبدال', remove: 'حذف', cancel: 'إلغاء', confirm: 'تأكيد الحذف', restore: 'استعادة', revoke: 'إلغاء الوصول', more: 'تحميل المزيد', status: 'فحص الحالة' }),
}
